platform := "x86_64-unknown-linux-musl"

build-program sdk_path program_path:
    ./scripts/build-program.sh "{{sdk_path}}" "{{program_path}}"

clone-devops-repo ref='master':
    @./scripts/clone_devops_repo.sh "{{ref}}"

download-sdk download_path release_version force="false" unpack="true":
    ./scripts/download-sdk.sh "{{platform}}" "{{download_path}}" "{{release_version}}" "{{force}}" "{{unpack}}"
