[target.x86_64-unknown-linux-musl]
linker = "x86_64-unknown-linux-musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-unknown-linux-musl-gcc"

[target.wasm32-unknown-unknown]
rustflags = ["-D", "warnings"]
