[package]
name = "test-programs"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20"

program-builder = { path = "../program-builder" }

[build-dependencies]
program-builder = { path = "../program-builder", features = ["compile"] }

[features]
default = []
