[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nada_test"
version = "0.1.0"
description = "Nillion Nada Test Framework"
requires-python = ">=3.10"
readme = "README.pyproject.md"
dependencies = []
classifiers = [
    "License :: OSI Approved :: MIT License",
]
license = { file = "../../../../LICENSE" }

[project.optional-dependencies]
lint = [
    "pylint>=2.17,<3.3"
]

[project.scripts]
nada-test = "nada_test.cli:main"

[tool.setuptools]
packages = ["nada_test"]

