[package]
name = "program-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rayon = { version = "1", optional = true }
tempfile = { version = "3.10", optional = true }
fslock = { version = "0.2.1", optional = true }

nada-compiler-backend = { path = "../compiler-backend" }
mpc-vm = { path = "../../libs/execution-engine/mpc-vm" }
pynadac = { path = "../pynadac", optional = true }

[features]
default = ["mpc-vm/serde", "parallel-build"]
compile = ["tempfile", "fslock", "pynadac"]
parallel-build = ["rayon"]
