[package]
name = "nada"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4.5.13", features = ["derive"] }
color-eyre = "0.6.3"
colored = "2.1.0"
env_logger = "0.11.5"
eyre = "0.6.12"
futures = "0.3"
humansize = "2.1.3"
humantime = "2.1.0"
indicatif = "0.17.8"
log = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.127"
serde_repr = "0.1"
tabled = { version = "0.16", features = ["ansi"] }
tokio = "1"
toml = "0.8.14"
toml_edit = "0.22"
uuid = "1.10"

tools-config = { path = "../libs/tools-config", features = ["client"] }
serde-files-utils = { path = "../../libs/serde-files-utils", default-features = false, features = [
    "json",
    "binary",
    "yaml",
] }
client-metrics = { path = "../../libs/client-metrics" }
file-find = { path = "../../libs/file-find" }
clap-utils = { path = "../../libs/clap-utils", features = ["shell-completions"] }
mpc-vm = { path = "../../libs/execution-engine/mpc-vm", features = ["simulator", "text_repr", "serde"] }
math_lib = { path = "../../libs/math" }
nada-compiler-backend = { path = "../../nada-lang/compiler-backend" }
pynadac = { path = "../../nada-lang/pynadac" }
program-auditor = { path = "../../nada-lang/program-auditor", features = ["serde"] }
bytecode-evaluator = { path = "../../nada-lang/bytecode-evaluator" }
nada-value = { path = "../../libs/nada-value", features = ["secret-serde", "secret-arithmetic", "json"] }
nada-values-args = { path = "../../libs/nada-values-args" }
nillion-client = { path = "../../client" }
