#!/usr/bin/env python

# pylint: disable=import-error, invalid-name

"""
The Ultimate Load Test Manager tool.
"""

import sys

from load_test_manager import commands, parse_args
from load_test_manager.errors import CommandError


def main():
    """
    Main driver.
    """
    args = parse_args.parse()

    # Run commands.
    try:
        if args.command == "grafana-snapshot":
            # pylint: disable=too-many-function-args
            commands.grafana_snapshot(
                args.uuid, args.start_time_secs, args.end_time_secs, args.env_name
            )
        elif args.command == "render-spec":
            # pylint: disable=too-many-function-args
            commands.render_spec(
                args.spec_path,
                args.max_flow_duration,
                args.max_test_duration,
                args.operation_input_size,
                args.workers,
                args.required_starting_balance,
            )
    except CommandError as ex:
        print(f"An error occurred running command '{args.command}': {ex}")
        sys.exit(1)


if __name__ == "__main__":
    main()
