[package]
name = "operations"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "operations-generator"
path = "src/bin/generator.rs"

[dependencies]
nada-value = { path = "../../libs/nada-value" }
anyhow = "1.0.86"
linked-hash-map = "0.5.6"
heck = "0.5"
itertools = "0.13.0"
strum = "0.26"
strum_macros = "0.27"
clap = { version = "4.5", features = ["derive"] }

[features]
default = []
