[package]
name = "nilup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
eyre = "0.6.12"
color-eyre = "0.6.3"
toml = "0.8.14"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.34"
dirs = "5.0.1"
tracing = "0.1.40"

object_store = { version = "0.11.1", features = ["aws"] }
tokio = { version = "1", features = ["full"] }
flate2 = "1.0.33"
tar = "0.4.43"

file-find = { path = "../../libs/file-find" }
client-metrics = { path = "../../libs/client-metrics" }
clap-utils = { path = "../../libs/clap-utils", features = ["shell-completions"] }
regex = "1.11.1"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
] }
futures-util = "0.3.31"
